require('./src/model/broken.test.js');
require('./src/model/document.test.js');
require('./src/model/statistic.test.js');
require('./src/util.test.js');
require('./src/based-option.test.js');
require('./src/based-rule.test.js');
require('./src/acts/config.test.js');
require('./src/reporters/base.test');
require('./src/checker.test.js');
