window.esdocSearchIndex = [
  [
    "bs-broken-links-checker/src/base.es6~base",
    "class/src/base.es6~Base.html",
    "<span>Base</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/base.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/based-option.es6~basedoption",
    "class/src/based-option.es6~BasedOption.html",
    "<span>BasedOption</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/based-option.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/model/broken.es6~brokenurls",
    "class/src/model/broken.es6~BrokenUrls.html",
    "<span>BrokenUrls</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/model/broken.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/checker.es6~checker",
    "class/src/checker.es6~Checker.html",
    "<span>Checker</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/checker.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/model/document.es6~document",
    "class/src/model/document.es6~Document.html",
    "<span>Document</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/model/document.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/link-analyzer.es6~linkanalyzer",
    "class/src/link-analyzer.es6~LinkAnalyzer.html",
    "<span>LinkAnalyzer</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/link-analyzer.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/model/model.es6~model",
    "class/src/model/model.es6~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/model/model.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/reporters/base.es6~reporterbase",
    "class/src/reporters/base.es6~ReporterBase.html",
    "<span>ReporterBase</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/reporters/base.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/reporters/html.es6~reporterhtml",
    "class/src/reporters/html.es6~ReporterHtml.html",
    "<span>ReporterHtml</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/reporters/html.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/reporters/json.es6~reporterjson",
    "class/src/reporters/json.es6~ReporterJson.html",
    "<span>ReporterJson</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/reporters/json.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/model/statistic.es6~statistic",
    "class/src/model/statistic.es6~Statistic.html",
    "<span>Statistic</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/model/statistic.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/util.es6~util",
    "class/src/util.es6~Util.html",
    "<span>Util</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/util.es6</span>",
    "class"
  ],
  [
    "bs-broken-links-checker/src/cli/cmd-config.es6~cmdconfig",
    "function/index.html#static-function-cmdconfig",
    "<span>cmdconfig</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/cli/cmd-config.es6</span>",
    "function"
  ],
  [
    "bs-broken-links-checker/src/cli/cmd-run.es6~cmdrun",
    "function/index.html#static-function-cmdrun",
    "<span>cmdrun</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/cli/cmd-run.es6</span>",
    "function"
  ],
  [
    "bs-broken-links-checker/src/cli/cmd-version.es6~cmdversion",
    "function/index.html#static-function-cmdversion",
    "<span>cmdversion</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/cli/cmd-version.es6</span>",
    "function"
  ],
  [
    "bs-broken-links-checker/src/acts/config.es6~createconfigfile",
    "function/index.html#static-function-createConfigFile",
    "<span>createConfigFile</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/acts/config.es6</span>",
    "function"
  ],
  [
    "bs-broken-links-checker/src/acts/config.es6~createconfigstub",
    "function/index.html#static-function-createConfigStub",
    "<span>createConfigStub</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/acts/config.es6</span>",
    "function"
  ],
  [
    "bs-broken-links-checker/src/acts/config.es6~createconfigsdir",
    "function/index.html#static-function-createConfigsDir",
    "<span>createConfigsDir</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/acts/config.es6</span>",
    "function"
  ],
  [
    "bs-broken-links-checker/src/acts/run.es6~run",
    "function/index.html#static-function-run",
    "<span>run</span> <span class=\"search-result-import-path\">bs-broken-links-checker/src/acts/run.es6</span>",
    "function"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber31",
    "BrokenLinksChecker",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber241",
    "BrokenLinksChecker check external urls",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber262",
    "BrokenLinksChecker check external urls should check and mark broken external link",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber252",
    "BrokenLinksChecker check external urls should check external link",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber293",
    "BrokenLinksChecker check external urls should mark url as valid if it was checked from second attempt",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber242",
    "BrokenLinksChecker check external urls should not check external link",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber276",
    "BrokenLinksChecker check external urls should not mark url as broken if timeout was occur for all attempts",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber168",
    "BrokenLinksChecker custom acceptedSchemes option value",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber182",
    "BrokenLinksChecker custom acceptedSchemes option value should check urls with schemes from array of acceptedSchemes",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber169",
    "BrokenLinksChecker custom acceptedSchemes option value should not check urls with another schemes",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber227",
    "BrokenLinksChecker custom excludeLinkPatterns option",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber228",
    "BrokenLinksChecker custom excludeLinkPatterns option should not check excluded urls",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber196",
    "BrokenLinksChecker custom requestHeaders option value",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber211",
    "BrokenLinksChecker custom requestHeaders option value should check url in case of accessible request headers",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber197",
    "BrokenLinksChecker custom requestHeaders option value should mark url as broken in case of not accessible request headers",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber143",
    "BrokenLinksChecker custom requestRetriesAmount option value",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber144",
    "BrokenLinksChecker custom requestRetriesAmount option value should mark url as broken if timeout was occur for all attempts",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber154",
    "BrokenLinksChecker custom requestRetriesAmount option value should mark url as valid if it was checked from second attempt",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber119",
    "BrokenLinksChecker custom timeout option value",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber120",
    "BrokenLinksChecker custom timeout option value should mark url as broken if timeout was occur",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber131",
    "BrokenLinksChecker custom timeout option value should mark url as valid if timeout is greater then server response time",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber82",
    "BrokenLinksChecker should not check same url twice (absolute url)",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber92",
    "BrokenLinksChecker should not check same url twice (relative url)",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber46",
    "BrokenLinksChecker should simply check broken url (404)",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber59",
    "BrokenLinksChecker should simply check broken url (500)",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber36",
    "BrokenLinksChecker should simply check given url",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber72",
    "BrokenLinksChecker should skip links without href attributes",
    "test"
  ],
  [
    "",
    "test-file/test/integration.test.js.html#lineNumber102",
    "BrokenLinksChecker should use pending queue for small concurrency",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber7",
    "LinkAnalyzer",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber8",
    "LinkAnalyzer constructor",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber19",
    "LinkAnalyzer constructor should have valid options field value after initialization",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber15",
    "LinkAnalyzer constructor should have valid url field value after initialization",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber24",
    "LinkAnalyzer isNeedToSkipUrl",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber163",
    "LinkAnalyzer isNeedToSkipUrl complex",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber177",
    "LinkAnalyzer isNeedToSkipUrl complex should pass \"http://my.site.com/url1\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber185",
    "LinkAnalyzer isNeedToSkipUrl complex should pass \"https://my.site.com/url1\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber173",
    "LinkAnalyzer isNeedToSkipUrl complex should skip \"http://google.com\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber181",
    "LinkAnalyzer isNeedToSkipUrl complex should skip \"http://my.site.com/foo1\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber189",
    "LinkAnalyzer isNeedToSkipUrl complex should skip \"mailto://my.site.com/foo2\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber169",
    "LinkAnalyzer isNeedToSkipUrl complex should skip \"mailto://my.site.com/url1\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber65",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber66",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should pass url if it does not matches any regular expression",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber116",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should pass url if it does not matches on any blacklisted urls",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber71",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url if it does matches at least one of regular expressions",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber76",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url if it equal to one of blacklisted urls",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber96",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url if it matches to \"*/foo/bar\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber91",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url if it matches to \"http://my.site.com/*\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber86",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url if it matches to \"http://my.site.com/*/bar\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber81",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url if it matches to \"http://my.site.com/foo/*\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber101",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url with anchor if it equal to one of to one of blacklisted urls",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber111",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url with anchor if it matches to \"http://my.site.com/*/bar#a\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber106",
    "LinkAnalyzer isNeedToSkipUrl excluded urls criteria should skip url with anchor if it matches to \"http://my.site.com/foo/*#a\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber43",
    "LinkAnalyzer isNeedToSkipUrl external criteria",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber44",
    "LinkAnalyzer isNeedToSkipUrl external criteria should pass external url if \"checkExternalUrls\" is set to true",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber59",
    "LinkAnalyzer isNeedToSkipUrl external criteria should pass internal url if \"checkExternalUrls\" is set to false",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber54",
    "LinkAnalyzer isNeedToSkipUrl external criteria should pass internal url if \"checkExternalUrls\" is set to true",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber49",
    "LinkAnalyzer isNeedToSkipUrl external criteria should skip external url if \"checkExternalUrls\" is set to false",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber122",
    "LinkAnalyzer isNeedToSkipUrl mode criteria",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber123",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"page\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber128",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"page\" should pass url if url of page where it is equals to root page",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber132",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"page\" should skip url if url of page where it does not equal to root page",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber137",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"section\"",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber145",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"section\" should pass url it is child against to root page",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber153",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"section\" should pass url it is parent to root page",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber149",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"section\" should pass url it is sibling to root page",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber157",
    "LinkAnalyzer isNeedToSkipUrl mode criteria mode \"section\" should skip url it from another section of website",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber33",
    "LinkAnalyzer isNeedToSkipUrl protocols criteria",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber38",
    "LinkAnalyzer isNeedToSkipUrl protocols criteria should pass url with accepted schema",
    "test"
  ],
  [
    "",
    "test-file/test/src/link-analyzer.test.js.html#lineNumber34",
    "LinkAnalyzer isNeedToSkipUrl protocols criteria should skip url with non-accepted schema",
    "test"
  ],
  [
    "",
    "test-file/test/src/reporters/base.test.js.html#lineNumber7",
    "Reporters",
    "test"
  ],
  [
    "",
    "test-file/test/src/reporters/base.test.js.html#lineNumber8",
    "Reporters Base",
    "test"
  ],
  [
    "",
    "test-file/test/src/reporters/base.test.js.html#lineNumber25",
    "Reporters Base should create report folder for given config name",
    "test"
  ],
  [
    "",
    "test-file/test/src/reporters/base.test.js.html#lineNumber20",
    "Reporters Base should create reports folder",
    "test"
  ],
  [
    "",
    "test-file/test/src/reporters/base.test.js.html#lineNumber30",
    "Reporters Base should save report file",
    "test"
  ],
  [
    "",
    "test-file/test/src/util.test.js.html#lineNumber4",
    "Util",
    "test"
  ],
  [
    "",
    "test-file/test/src/util.test.js.html#lineNumber5",
    "Util should can be initialized",
    "test"
  ],
  [
    "",
    "test-file/test/src/util.test.js.html#lineNumber10",
    "Util should return valid path to configuration folder",
    "test"
  ],
  [
    "",
    "test-file/test/src/util.test.js.html#lineNumber14",
    "Util should return valid path to reports folder",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/config.test.js.html#lineNumber7",
    "acts/config",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/config.test.js.html#lineNumber31",
    "acts/config should create configuration directory",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/config.test.js.html#lineNumber40",
    "acts/config should create configuration file",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/config.test.js.html#lineNumber36",
    "acts/config should create configuration stub",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/run.test.js.html#lineNumber8",
    "acts/run",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/run.test.js.html#lineNumber30",
    "acts/run execute run action",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/run.test.js.html#lineNumber41",
    "acts/run execute run action with custom params",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/run.test.js.html#lineNumber37",
    "acts/run execute run action with default params",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/run.test.js.html#lineNumber26",
    "acts/run should throw error if config file is missed",
    "test"
  ],
  [
    "",
    "test-file/test/src/acts/run.test.js.html#lineNumber22",
    "acts/run should throw error if config param was not set",
    "test"
  ],
  [
    "",
    "test-file/test/src/based-option.test.js.html#lineNumber3",
    "based-option",
    "test"
  ],
  [
    "",
    "test-file/test/src/based-option.test.js.html#lineNumber10",
    "based-option setOption",
    "test"
  ],
  [
    "",
    "test-file/test/src/based-option.test.js.html#lineNumber16",
    "based-option setOption should set default value if option was not set",
    "test"
  ],
  [
    "",
    "test-file/test/src/based-option.test.js.html#lineNumber11",
    "based-option setOption should set option value for given option name",
    "test"
  ],
  [
    "",
    "test-file/test/src/based-option.test.js.html#lineNumber22",
    "based-option should get valid option value",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber4",
    "broken",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber17",
    "broken add",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber18",
    "broken add should add broken links model item to list of broken links",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber70",
    "broken clear",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber75",
    "broken clear should clear broken link items model",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber71",
    "broken clear should return instance of BrokenUrls class",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber11",
    "broken constructor",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber12",
    "broken constructor should initialize empty broken urls model after initialization",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber85",
    "broken create",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber86",
    "broken create should create BrokenUrls instance by static method",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber30",
    "broken getAll",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber31",
    "broken getAll should return all broke link items from model",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber39",
    "broken getByCode",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber46",
    "broken getByCode should return valid set of broken link items by given status code",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber60",
    "broken getByCode should return valid set of broken link items by status code 404",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/broken.test.js.html#lineNumber64",
    "broken getByCode should return valid set of broken link items by status code 500",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber7",
    "checker",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber81",
    "checker _getRequestOptions",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber82",
    "checker _getRequestOptions should return valid request options object",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber8",
    "checker constructor",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber28",
    "checker constructor should be initialized with default params if options are empty",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber24",
    "checker constructor should be initialized with default params if options were not set",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber52",
    "checker constructor should override default acceptedSchemes rule",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber57",
    "checker constructor should override default checkExternalUrls option",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber32",
    "checker constructor should override default concurrent option",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber62",
    "checker constructor should override default excludeLinkPatterns rule",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber37",
    "checker constructor should override default requestHeaders option",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber42",
    "checker constructor should override default requestRetriesAmount option",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber47",
    "checker constructor should override default requestTimeout option",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber92",
    "checker should have default onDone handler",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber69",
    "checker start",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber75",
    "checker start should throw error if url param has invalid format",
    "test"
  ],
  [
    "",
    "test-file/test/src/checker.test.js.html#lineNumber70",
    "checker start should throw error if url param was not set",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber5",
    "document",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber17",
    "document constructor",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber26",
    "document constructor should set value to _$ field",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber18",
    "document constructor should set value to _res field",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber22",
    "document constructor should set value to _url field",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber39",
    "document should have $ getter",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber31",
    "document should have res getter",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber35",
    "document should have url getter",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/document.test.js.html#lineNumber43",
    "document should resolve link url based on _url",
    "test"
  ],
  [
    "src/acts/config.es6",
    "file/src/acts/config.es6.html",
    "src/acts/config.es6",
    "file"
  ],
  [
    "src/acts/run.es6",
    "file/src/acts/run.es6.html",
    "src/acts/run.es6",
    "file"
  ],
  [
    "src/base.es6",
    "file/src/base.es6.html",
    "src/base.es6",
    "file"
  ],
  [
    "src/base.es6~base#_logger",
    "class/src/base.es6~Base.html#instance-member-_logger",
    "src/base.es6~Base#_logger",
    "member"
  ],
  [
    "src/base.es6~base#constructor",
    "class/src/base.es6~Base.html#instance-constructor-constructor",
    "src/base.es6~Base#constructor",
    "method"
  ],
  [
    "src/based-option.es6",
    "file/src/based-option.es6.html",
    "src/based-option.es6",
    "file"
  ],
  [
    "src/based-option.es6~basedoption#_options",
    "class/src/based-option.es6~BasedOption.html#instance-member-_options",
    "src/based-option.es6~BasedOption#_options",
    "member"
  ],
  [
    "src/based-option.es6~basedoption#getoption",
    "class/src/based-option.es6~BasedOption.html#instance-method-getOption",
    "src/based-option.es6~BasedOption#getOption",
    "method"
  ],
  [
    "src/based-option.es6~basedoption#setoption",
    "class/src/based-option.es6~BasedOption.html#instance-method-setOption",
    "src/based-option.es6~BasedOption#setOption",
    "method"
  ],
  [
    "src/checker.es6",
    "file/src/checker.es6.html",
    "src/checker.es6",
    "file"
  ],
  [
    "src/checker.es6~checker#_addtoqueue",
    "class/src/checker.es6~Checker.html#instance-method-_addToQueue",
    "src/checker.es6~Checker#_addToQueue",
    "method"
  ],
  [
    "src/checker.es6~checker#_checkexternallink",
    "class/src/checker.es6~Checker.html#instance-method-_checkExternalLink",
    "src/checker.es6~Checker#_checkExternalLink",
    "method"
  ],
  [
    "src/checker.es6~checker#_checkexternallinks",
    "class/src/checker.es6~Checker.html#instance-method-_checkExternalLinks",
    "src/checker.es6~Checker#_checkExternalLinks",
    "method"
  ],
  [
    "src/checker.es6~checker#_checkinternallink",
    "class/src/checker.es6~Checker.html#instance-method-_checkInternalLink",
    "src/checker.es6~Checker#_checkInternalLink",
    "method"
  ],
  [
    "src/checker.es6~checker#_getrequestoptions",
    "class/src/checker.es6~Checker.html#instance-method-_getRequestOptions",
    "src/checker.es6~Checker#_getRequestOptions",
    "method"
  ],
  [
    "src/checker.es6~checker#_linkanalyzer",
    "class/src/checker.es6~Checker.html#instance-member-_linkAnalyzer",
    "src/checker.es6~Checker#_linkAnalyzer",
    "member"
  ],
  [
    "src/checker.es6~checker#_model",
    "class/src/checker.es6~Checker.html#instance-member-_model",
    "src/checker.es6~Checker#_model",
    "member"
  ],
  [
    "src/checker.es6~checker#_onfinishload",
    "class/src/checker.es6~Checker.html#instance-method-_onFinishLoad",
    "src/checker.es6~Checker#_onFinishLoad",
    "method"
  ],
  [
    "src/checker.es6~checker#_options",
    "class/src/checker.es6~Checker.html#instance-member-_options",
    "src/checker.es6~Checker#_options",
    "member"
  ],
  [
    "src/checker.es6~checker#_statistic",
    "class/src/checker.es6~Checker.html#instance-member-_statistic",
    "src/checker.es6~Checker#_statistic",
    "member"
  ],
  [
    "src/checker.es6~checker#constructor",
    "class/src/checker.es6~Checker.html#instance-constructor-constructor",
    "src/checker.es6~Checker#constructor",
    "method"
  ],
  [
    "src/checker.es6~checker#initlinkanalyzer",
    "class/src/checker.es6~Checker.html#instance-method-initLinkAnalyzer",
    "src/checker.es6~Checker#initLinkAnalyzer",
    "method"
  ],
  [
    "src/checker.es6~checker#initmodel",
    "class/src/checker.es6~Checker.html#instance-method-initModel",
    "src/checker.es6~Checker#initModel",
    "method"
  ],
  [
    "src/checker.es6~checker#initstatistic",
    "class/src/checker.es6~Checker.html#instance-method-initStatistic",
    "src/checker.es6~Checker#initStatistic",
    "method"
  ],
  [
    "src/checker.es6~checker#linkanalyzer",
    "class/src/checker.es6~Checker.html#instance-get-linkAnalyzer",
    "src/checker.es6~Checker#linkAnalyzer",
    "member"
  ],
  [
    "src/checker.es6~checker#logger",
    "class/src/checker.es6~Checker.html#instance-get-logger",
    "src/checker.es6~Checker#logger",
    "member"
  ],
  [
    "src/checker.es6~checker#model",
    "class/src/checker.es6~Checker.html#instance-get-model",
    "src/checker.es6~Checker#model",
    "member"
  ],
  [
    "src/checker.es6~checker#ondone",
    "class/src/checker.es6~Checker.html#instance-method-onDone",
    "src/checker.es6~Checker#onDone",
    "method"
  ],
  [
    "src/checker.es6~checker#options",
    "class/src/checker.es6~Checker.html#instance-get-options",
    "src/checker.es6~Checker#options",
    "member"
  ],
  [
    "src/checker.es6~checker#processloadeddocument",
    "class/src/checker.es6~Checker.html#instance-method-processLoadedDocument",
    "src/checker.es6~Checker#processLoadedDocument",
    "method"
  ],
  [
    "src/checker.es6~checker#start",
    "class/src/checker.es6~Checker.html#instance-method-start",
    "src/checker.es6~Checker#start",
    "method"
  ],
  [
    "src/checker.es6~checker#statistic",
    "class/src/checker.es6~Checker.html#instance-get-statistic",
    "src/checker.es6~Checker#statistic",
    "member"
  ],
  [
    "src/checker.es6~checker.constants",
    "class/src/checker.es6~Checker.html#static-get-CONSTANTS",
    "src/checker.es6~Checker.CONSTANTS",
    "member"
  ],
  [
    "src/checker.es6~checker.default",
    "class/src/checker.es6~Checker.html#static-get-DEFAULT",
    "src/checker.es6~Checker.DEFAULT",
    "member"
  ],
  [
    "src/cli/cmd-config.es6",
    "file/src/cli/cmd-config.es6.html",
    "src/cli/cmd-config.es6",
    "file"
  ],
  [
    "src/cli/cmd-run.es6",
    "file/src/cli/cmd-run.es6.html",
    "src/cli/cmd-run.es6",
    "file"
  ],
  [
    "src/cli/cmd-version.es6",
    "file/src/cli/cmd-version.es6.html",
    "src/cli/cmd-version.es6",
    "file"
  ],
  [
    "src/cli/coa.es6",
    "file/src/cli/coa.es6.html",
    "src/cli/coa.es6",
    "file"
  ],
  [
    "src/link-analyzer.es6",
    "file/src/link-analyzer.es6.html",
    "src/link-analyzer.es6",
    "file"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#_options",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-member-_options",
    "src/link-analyzer.es6~LinkAnalyzer#_options",
    "member"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#_skipexcludedurls",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-method-_skipExcludedUrls",
    "src/link-analyzer.es6~LinkAnalyzer#_skipExcludedUrls",
    "method"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#_skipexternalurls",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-method-_skipExternalUrls",
    "src/link-analyzer.es6~LinkAnalyzer#_skipExternalUrls",
    "method"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#_skipnonacceptableprotocols",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-method-_skipNonAcceptableProtocols",
    "src/link-analyzer.es6~LinkAnalyzer#_skipNonAcceptableProtocols",
    "method"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#_skiponmode",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-method-_skipOnMode",
    "src/link-analyzer.es6~LinkAnalyzer#_skipOnMode",
    "method"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#_url",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-member-_url",
    "src/link-analyzer.es6~LinkAnalyzer#_url",
    "member"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#constructor",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-constructor-constructor",
    "src/link-analyzer.es6~LinkAnalyzer#constructor",
    "method"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#isexternal",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-method-isExternal",
    "src/link-analyzer.es6~LinkAnalyzer#isExternal",
    "method"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#isneedtoskipurl",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-method-isNeedToSkipUrl",
    "src/link-analyzer.es6~LinkAnalyzer#isNeedToSkipUrl",
    "method"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#options",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-get-options",
    "src/link-analyzer.es6~LinkAnalyzer#options",
    "member"
  ],
  [
    "src/link-analyzer.es6~linkanalyzer#url",
    "class/src/link-analyzer.es6~LinkAnalyzer.html#instance-get-url",
    "src/link-analyzer.es6~LinkAnalyzer#url",
    "member"
  ],
  [
    "src/model/broken.es6",
    "file/src/model/broken.es6.html",
    "src/model/broken.es6",
    "file"
  ],
  [
    "src/model/broken.es6~brokenurls#_urls",
    "class/src/model/broken.es6~BrokenUrls.html#instance-member-_urls",
    "src/model/broken.es6~BrokenUrls#_urls",
    "member"
  ],
  [
    "src/model/broken.es6~brokenurls#add",
    "class/src/model/broken.es6~BrokenUrls.html#instance-method-add",
    "src/model/broken.es6~BrokenUrls#add",
    "method"
  ],
  [
    "src/model/broken.es6~brokenurls#clear",
    "class/src/model/broken.es6~BrokenUrls.html#instance-method-clear",
    "src/model/broken.es6~BrokenUrls#clear",
    "method"
  ],
  [
    "src/model/broken.es6~brokenurls#constructor",
    "class/src/model/broken.es6~BrokenUrls.html#instance-constructor-constructor",
    "src/model/broken.es6~BrokenUrls#constructor",
    "method"
  ],
  [
    "src/model/broken.es6~brokenurls#get404",
    "class/src/model/broken.es6~BrokenUrls.html#instance-method-get404",
    "src/model/broken.es6~BrokenUrls#get404",
    "method"
  ],
  [
    "src/model/broken.es6~brokenurls#get500",
    "class/src/model/broken.es6~BrokenUrls.html#instance-method-get500",
    "src/model/broken.es6~BrokenUrls#get500",
    "method"
  ],
  [
    "src/model/broken.es6~brokenurls#getall",
    "class/src/model/broken.es6~BrokenUrls.html#instance-method-getAll",
    "src/model/broken.es6~BrokenUrls#getAll",
    "method"
  ],
  [
    "src/model/broken.es6~brokenurls#getbycode",
    "class/src/model/broken.es6~BrokenUrls.html#instance-method-getByCode",
    "src/model/broken.es6~BrokenUrls#getByCode",
    "method"
  ],
  [
    "src/model/broken.es6~brokenurls.create",
    "class/src/model/broken.es6~BrokenUrls.html#static-method-create",
    "src/model/broken.es6~BrokenUrls.create",
    "method"
  ],
  [
    "src/model/document.es6",
    "file/src/model/document.es6.html",
    "src/model/document.es6",
    "file"
  ],
  [
    "src/model/document.es6~document#$",
    "class/src/model/document.es6~Document.html#instance-get-$",
    "src/model/document.es6~Document#$",
    "member"
  ],
  [
    "src/model/document.es6~document#_$",
    "class/src/model/document.es6~Document.html#instance-member-_$",
    "src/model/document.es6~Document#_$",
    "member"
  ],
  [
    "src/model/document.es6~document#_res",
    "class/src/model/document.es6~Document.html#instance-member-_res",
    "src/model/document.es6~Document#_res",
    "member"
  ],
  [
    "src/model/document.es6~document#_url",
    "class/src/model/document.es6~Document.html#instance-member-_url",
    "src/model/document.es6~Document#_url",
    "member"
  ],
  [
    "src/model/document.es6~document#constructor",
    "class/src/model/document.es6~Document.html#instance-constructor-constructor",
    "src/model/document.es6~Document#constructor",
    "method"
  ],
  [
    "src/model/document.es6~document#res",
    "class/src/model/document.es6~Document.html#instance-get-res",
    "src/model/document.es6~Document#res",
    "member"
  ],
  [
    "src/model/document.es6~document#resolve",
    "class/src/model/document.es6~Document.html#instance-method-resolve",
    "src/model/document.es6~Document#resolve",
    "method"
  ],
  [
    "src/model/document.es6~document#url",
    "class/src/model/document.es6~Document.html#instance-get-url",
    "src/model/document.es6~Document#url",
    "member"
  ],
  [
    "src/model/model.es6",
    "file/src/model/model.es6.html",
    "src/model/model.es6",
    "file"
  ],
  [
    "src/model/model.es6~model#_active",
    "class/src/model/model.es6~Model.html#instance-member-_active",
    "src/model/model.es6~Model#_active",
    "member"
  ],
  [
    "src/model/model.es6~model#_external",
    "class/src/model/model.es6~Model.html#instance-member-_external",
    "src/model/model.es6~Model#_external",
    "member"
  ],
  [
    "src/model/model.es6~model#_pending",
    "class/src/model/model.es6~Model.html#instance-member-_pending",
    "src/model/model.es6~Model#_pending",
    "member"
  ],
  [
    "src/model/model.es6~model#_processed",
    "class/src/model/model.es6~Model.html#instance-member-_processed",
    "src/model/model.es6~Model#_processed",
    "member"
  ],
  [
    "src/model/model.es6~model#addtoactive",
    "class/src/model/model.es6~Model.html#instance-method-addToActive",
    "src/model/model.es6~Model#addToActive",
    "method"
  ],
  [
    "src/model/model.es6~model#addtoexternal",
    "class/src/model/model.es6~Model.html#instance-method-addToExternal",
    "src/model/model.es6~Model#addToExternal",
    "method"
  ],
  [
    "src/model/model.es6~model#addtopending",
    "class/src/model/model.es6~Model.html#instance-method-addToPending",
    "src/model/model.es6~Model#addToPending",
    "method"
  ],
  [
    "src/model/model.es6~model#addtoprocessed",
    "class/src/model/model.es6~Model.html#instance-method-addToProcessed",
    "src/model/model.es6~Model#addToProcessed",
    "method"
  ],
  [
    "src/model/model.es6~model#areactive",
    "class/src/model/model.es6~Model.html#instance-method-areActive",
    "src/model/model.es6~Model#areActive",
    "method"
  ],
  [
    "src/model/model.es6~model#areexternal",
    "class/src/model/model.es6~Model.html#instance-method-areExternal",
    "src/model/model.es6~Model#areExternal",
    "method"
  ],
  [
    "src/model/model.es6~model#constructor",
    "class/src/model/model.es6~Model.html#instance-constructor-constructor",
    "src/model/model.es6~Model#constructor",
    "method"
  ],
  [
    "src/model/model.es6~model#external",
    "class/src/model/model.es6~Model.html#instance-get-external",
    "src/model/model.es6~Model#external",
    "member"
  ],
  [
    "src/model/model.es6~model#getactivelength",
    "class/src/model/model.es6~Model.html#instance-method-getActiveLength",
    "src/model/model.es6~Model#getActiveLength",
    "method"
  ],
  [
    "src/model/model.es6~model#getpendinglength",
    "class/src/model/model.es6~Model.html#instance-method-getPendingLength",
    "src/model/model.es6~Model#getPendingLength",
    "method"
  ],
  [
    "src/model/model.es6~model#isqueuefull",
    "class/src/model/model.es6~Model.html#instance-method-isQueueFull",
    "src/model/model.es6~Model#isQueueFull",
    "method"
  ],
  [
    "src/model/model.es6~model#removefromactive",
    "class/src/model/model.es6~Model.html#instance-method-removeFromActive",
    "src/model/model.es6~Model#removeFromActive",
    "method"
  ],
  [
    "src/model/model.es6~model#removefrompending",
    "class/src/model/model.es6~Model.html#instance-method-removeFromPending",
    "src/model/model.es6~Model#removeFromPending",
    "method"
  ],
  [
    "src/model/statistic.es6",
    "file/src/model/statistic.es6.html",
    "src/model/statistic.es6",
    "file"
  ],
  [
    "src/model/statistic.es6~statistic#_broken",
    "class/src/model/statistic.es6~Statistic.html#instance-member-_broken",
    "src/model/statistic.es6~Statistic#_broken",
    "member"
  ],
  [
    "src/model/statistic.es6~statistic#_countexternal",
    "class/src/model/statistic.es6~Statistic.html#instance-member-_countExternal",
    "src/model/statistic.es6~Statistic#_countExternal",
    "member"
  ],
  [
    "src/model/statistic.es6~statistic#_countinternal",
    "class/src/model/statistic.es6~Statistic.html#instance-member-_countInternal",
    "src/model/statistic.es6~Statistic#_countInternal",
    "member"
  ],
  [
    "src/model/statistic.es6~statistic#constructor",
    "class/src/model/statistic.es6~Statistic.html#instance-constructor-constructor",
    "src/model/statistic.es6~Statistic#constructor",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic#getallcount",
    "class/src/model/statistic.es6~Statistic.html#instance-method-getAllCount",
    "src/model/statistic.es6~Statistic#getAllCount",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic#getbroken",
    "class/src/model/statistic.es6~Statistic.html#instance-method-getBroken",
    "src/model/statistic.es6~Statistic#getBroken",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic#getbrokencount",
    "class/src/model/statistic.es6~Statistic.html#instance-method-getBrokenCount",
    "src/model/statistic.es6~Statistic#getBrokenCount",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic#getexternalcount",
    "class/src/model/statistic.es6~Statistic.html#instance-method-getExternalCount",
    "src/model/statistic.es6~Statistic#getExternalCount",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic#getinternalcount",
    "class/src/model/statistic.es6~Statistic.html#instance-method-getInternalCount",
    "src/model/statistic.es6~Statistic#getInternalCount",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic#increaseexternalcount",
    "class/src/model/statistic.es6~Statistic.html#instance-method-increaseExternalCount",
    "src/model/statistic.es6~Statistic#increaseExternalCount",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic#increaseinternalcount",
    "class/src/model/statistic.es6~Statistic.html#instance-method-increaseInternalCount",
    "src/model/statistic.es6~Statistic#increaseInternalCount",
    "method"
  ],
  [
    "src/model/statistic.es6~statistic.create",
    "class/src/model/statistic.es6~Statistic.html#static-method-create",
    "src/model/statistic.es6~Statistic.create",
    "method"
  ],
  [
    "src/reporters/base.es6",
    "file/src/reporters/base.es6.html",
    "src/reporters/base.es6",
    "file"
  ],
  [
    "src/reporters/base.es6~reporterbase#_logger",
    "class/src/reporters/base.es6~ReporterBase.html#instance-member-_logger",
    "src/reporters/base.es6~ReporterBase#_logger",
    "member"
  ],
  [
    "src/reporters/base.es6~reporterbase#constructor",
    "class/src/reporters/base.es6~ReporterBase.html#instance-constructor-constructor",
    "src/reporters/base.es6~ReporterBase#constructor",
    "method"
  ],
  [
    "src/reporters/base.es6~reporterbase#createreportfolder",
    "class/src/reporters/base.es6~ReporterBase.html#instance-method-createReportFolder",
    "src/reporters/base.es6~ReporterBase#createReportFolder",
    "method"
  ],
  [
    "src/reporters/base.es6~reporterbase#createreportsfolder",
    "class/src/reporters/base.es6~ReporterBase.html#instance-method-createReportsFolder",
    "src/reporters/base.es6~ReporterBase#createReportsFolder",
    "method"
  ],
  [
    "src/reporters/base.es6~reporterbase#savereportfile",
    "class/src/reporters/base.es6~ReporterBase.html#instance-method-saveReportFile",
    "src/reporters/base.es6~ReporterBase#saveReportFile",
    "method"
  ],
  [
    "src/reporters/html.es6",
    "file/src/reporters/html.es6.html",
    "src/reporters/html.es6",
    "file"
  ],
  [
    "src/reporters/html.es6~reporterhtml#createreport",
    "class/src/reporters/html.es6~ReporterHtml.html#instance-method-createReport",
    "src/reporters/html.es6~ReporterHtml#createReport",
    "method"
  ],
  [
    "src/reporters/json.es6",
    "file/src/reporters/json.es6.html",
    "src/reporters/json.es6",
    "file"
  ],
  [
    "src/reporters/json.es6~reporterjson#createreport",
    "class/src/reporters/json.es6~ReporterJson.html#instance-method-createReport",
    "src/reporters/json.es6~ReporterJson#createReport",
    "method"
  ],
  [
    "src/util.es6",
    "file/src/util.es6.html",
    "src/util.es6",
    "file"
  ],
  [
    "src/util.es6~util.getconfigurationdirectory",
    "class/src/util.es6~Util.html#static-method-getConfigurationDirectory",
    "src/util.es6~Util.getConfigurationDirectory",
    "method"
  ],
  [
    "src/util.es6~util.getreportsdirectory",
    "class/src/util.es6~Util.html#static-method-getReportsDirectory",
    "src/util.es6~Util.getReportsDirectory",
    "method"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber5",
    "statistic",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber12",
    "statistic __constructor",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber21",
    "statistic __constructor should have empty broken links model after initialization",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber13",
    "statistic __constructor should have zero _countExternal value after initialization",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber17",
    "statistic __constructor should have zero _countInternal value after initialization",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber31",
    "statistic should increase external count",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber26",
    "statistic should increase internal count",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber55",
    "statistic should return broken links model",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber63",
    "statistic should return instance of Statistic class by create static method",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber48",
    "statistic should return valid count of all processed urls",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber42",
    "statistic should return valid external count value",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber36",
    "statistic should return valid internal count value",
    "test"
  ],
  [
    "",
    "test-file/test/src/model/statistic.test.js.html#lineNumber59",
    "statistic should return valid result of getBrokenCount method",
    "test"
  ],
  [
    "test/integration.test.js",
    "test-file/test/integration.test.js.html",
    "test/integration.test.js",
    "testFile"
  ],
  [
    "test/src/acts/config.test.js",
    "test-file/test/src/acts/config.test.js.html",
    "test/src/acts/config.test.js",
    "testFile"
  ],
  [
    "test/src/acts/run.test.js",
    "test-file/test/src/acts/run.test.js.html",
    "test/src/acts/run.test.js",
    "testFile"
  ],
  [
    "test/src/based-option.test.js",
    "test-file/test/src/based-option.test.js.html",
    "test/src/based-option.test.js",
    "testFile"
  ],
  [
    "test/src/checker.test.js",
    "test-file/test/src/checker.test.js.html",
    "test/src/checker.test.js",
    "testFile"
  ],
  [
    "test/src/link-analyzer.test.js",
    "test-file/test/src/link-analyzer.test.js.html",
    "test/src/link-analyzer.test.js",
    "testFile"
  ],
  [
    "test/src/model/broken.test.js",
    "test-file/test/src/model/broken.test.js.html",
    "test/src/model/broken.test.js",
    "testFile"
  ],
  [
    "test/src/model/document.test.js",
    "test-file/test/src/model/document.test.js.html",
    "test/src/model/document.test.js",
    "testFile"
  ],
  [
    "test/src/model/statistic.test.js",
    "test-file/test/src/model/statistic.test.js.html",
    "test/src/model/statistic.test.js",
    "testFile"
  ],
  [
    "test/src/reporters/base.test.js",
    "test-file/test/src/reporters/base.test.js.html",
    "test/src/reporters/base.test.js",
    "testFile"
  ],
  [
    "test/src/util.test.js",
    "test-file/test/src/util.test.js.html",
    "test/src/util.test.js",
    "testFile"
  ]
]